name: Build apk

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build_variant:
        description: "Variant to build (e.g., qaRelease)"
        type: string
        default: "qaRelease"
    outputs:
      artifact-name:
        description: "Generated APK artifact name"
        value: ${{ jobs.build_apk.outputs.artifact-name }}

jobs:

  # Builds the app with QA variant and publish the apk
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-outputs.outputs.artifact-name }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone external repo
        run: git clone https://github.com/owncloud/android.git android-app

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        working-directory: android-app
        run: ./gradlew clean assemble${{ inputs.build_variant }}

      - name: Set artifact name
        id: set-outputs
        run: |
          DATE=$(date +%Y%m%d-%H%M)
          COMMIT=$(git rev-parse --short HEAD)
          NAME="ownCloud${{ inputs.build_variant }}-${COMMIT}-${DATE}.apk"
          cp ./android-app/owncloudApp/build/outputs/apk/qa/release/owncloud_*-qa-release*.apk ./$NAME
          echo "artifact-name=$NAME" >> $GITHUB_OUTPUT
          ls -al .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-outputs.outputs.artifact-name }}
          path: ./${{ steps.set-outputs.outputs.artifact-name }}
