name: Clean up backend

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  remove_server:
    name: Remove server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Ansible
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # To prevent prompts waiting
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Create ansible inventory
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "[ocis_server]" > ./server/ansible/hosts.ini
          echo "${SSH_HOST} ansible_user=${SSH_USER} ansible_ssh_private_key_file=$HOME/.ssh/id_ed25519" >> ./server/ansible/hosts.ini

      - name: Run clean up
        run: |
          cd ./server/ansible
          ansible ocis_server -i hosts.ini -m shell -a \
            'containers=$(docker ps -aq); [ -n "$containers" ] && docker rm -f $containers'
          ansible ocis_server -i hosts.ini -m shell -a \
            'images=$(docker images -aq); [ -n "$images" ] && docker rmi -f $images'

