name: Execute tests

on:
  workflow_call:
    inputs:
      apk:
        description: '.apk to execute'
        type: string
      backend:
        description: 'type of backend'
        type: string
    secrets:
      oc_server_url:
        description: 'server url'

jobs:

  run_tests:
    name: Run Emulator & Execute Tests & Artifacts
    runs-on: ubuntu-latest
    env:
      OC_SERVER_URL: ${{ secrets.oc_server_url }}
      BACKEND:  ${{ inputs.backend }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      # Uploaded in the above
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.apk }}
          path: ./src/test/resources

      # Improves emulator's performance by using hardware acceleration
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Appium
        run: |
          mkdir -p logs video
          chmod +x ./runAppium.sh
          ./runAppium.sh

      - name: Run Emulator & Tests
        uses: reactivecircus/android-emulator-runner@v2
        id: execution
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_5
          avd-name: test-avd
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-snapshot -no-window -no-audio -no-boot-anim -accel on -memory 3072
          # Ignored tests, no oCIS tests and no CI tests will not run
          script: ./executeTests -t "not @ignore and not @noocis and not @noci"

      - name: Upload html report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: target/my-report.html

      - name: Rename log file
        if: always()
        run: |
          cp logs/*.log logs/log.log

      - name: Upload Execution Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs/log.log

      - name: Zip video files
        if: always()
        run: zip -r -9 test-recordings.zip video

      - name: Upload Video
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: video
          path: ./test-recordings.zip
